subjectArea:
  code: STAT
  description: Statistics

title: Course Overview

catalogNumber:
  formatted: '999'
  number: '999'
  prefix: ''
  suffix: ''

description: |
  This is a GitHub Pages template based on Just the Class, developed for
  the purpose of quickly deploying course overview websites. Such websites
  link to previous course offerings, provide a summary of what the course
  is about, and may list learning goals and prerequisites. This paragraph
  would normally be replaced by the description of a specific course, and
  could include information from the [Berkeley Academic
  Guide](https://guide.berkeley.edu/courses/stat/).'

  After instantiating this template, set the following secrets and variables
  in the new repository.

  | Type     | Name                 | Value |
  |----------|----------------------|-------|
  | Secret   | SIS_COURSE_API_ID    | `app_id` of [Course API credential](https://developers.api.berkeley.edu/api/100/credentials) |
  | Secret   | SIS_COURSE_API_KEY   | `app_key` of [Course API credential](https://developers.api.berkeley.edu/api/100/credentials) |
  | Variable | SIS_SUBJECT_AREA     | SIS subject area code, e.g. `STAT` |
  | Variable | SIS_COURSE_NUMBER    | SIS course number, e.g. `243` |
  | Variable | GOOGLE_ANALYTICS_TAG | Google Analytics tag, e.g. `G-...` |
  | Variable | AUTHOR               | Jekyll website author, e.g. `Course Staff` |
  | Variable | GIT_NAME             | Git `user.name` for GitHub Action commits, e.g. `GitHub Actions` |
  | Variable | GIT_EMAIL            | Git `user.email` for GitHub Action commits, e.g. `unit@dept.berkeley.edu` |
  | Variable | COURSE_DATA_FILE     | Path to YAML file, e.g. `.github/workflows/override.yml, containing SIS course data. Data in this file will override anything retrieved from the SIS. |

formatsOffered:
  description: |
    (Example from SIS) Three hours of lecture and two hours of laboratory
    per week. Six hours of lecture and three hours of laboratory per week
    for 8 weeks.

preparation:
  requiredText: |
    (Example from SIS) Mathematics 1A, Mathematics 16A, Mathematics
    10A/10B, or consent of instructor.

